KURSACH/urls.py
import allauth
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
# from django.contrib import admin
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),

    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),

]

urlpatterns += i18n_patterns(
    path('accounts/', include('allauth.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', include('main.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from .views import AnimationView, OnlyMoviesView, ComedyGenreView, HorrorGenreView, CartoonGenreView, \
    ActionFilmGenreView, FantasticGenreView, TrillerGenreView, SearchBar, MoviesView, MovieDetailView, AddReview, \
    MoviesDetailAPIView, ReviewsCreateFilmAPIView, MoscinoSaturn, CinemasAPIView, CinemasCreateAPIView, MovieViewSet

from rest_framework import routers


urlpatterns = [
    path('', MoviesView.as_view()),
    path('moscino-saturn', MoscinoSaturn.as_view()),
    path('animations/', AnimationView.as_view()),
    path('films/', OnlyMoviesView.as_view()),
    path('comedy/', ComedyGenreView.as_view()),
    path('horror/', HorrorGenreView.as_view()),
    path('cartoon/', CartoonGenreView.as_view()),
    path('action_film/', ActionFilmGenreView.as_view()),
    path('fantastic/', FantasticGenreView.as_view()),
    path('triller/', TrillerGenreView.as_view()),
    path('search/', SearchBar.as_view(), name='search'),
    path("<slug:slug>/", MovieDetailView.as_view(), name="movie_detail"),
    path('review/<int:pk>/', AddReview.as_view(), name='add_review'),
    path('api/v1/movies', views.MovieViewSet.as_view({'get': 'list'})),
    path('api/v1/cinemas', CinemasCreateAPIView.as_view()),
    path('api/v1/movies/<int:pk>', MovieViewSet.as_view({'get': 'retrieve'})),
    path('api/v1/review', ReviewsCreateFilmAPIView.as_view()),

    path('export_to_csv', views.export_to_csv, name='export_to_csv')
]

main/models.py
from django.db import models
from django.urls import reverse
from simple_history.models import HistoricalRecords

class Cinemas(models.Model):
    # Список доступных кинотеатров
    name = models.CharField('Кинотеатр', max_length=150)
    description = models.TextField('Описание')
    number = models.PositiveSmallIntegerField('Контактный номер', help_text='Введите номер кинотеатра')
    address = models.CharField('Адрес кинотеатра', max_length=150)
    url = models.SlugField(max_length=150, unique=True)


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Кинотеатр'
        verbose_name_plural = 'Кинотеатры'


class Categories(models.Model):
    # Список категорий
    name = models.CharField('Категория', max_length=150)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=150, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Genre(models.Model):
    # Список жанров
    name = models.CharField('Жанр', max_length=100, help_text='')
    description = models.TextField('Описание')
    url = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Actors(models.Model):
    # Актеры
    name = models.CharField('Имя', max_length=100)
    age = models.PositiveSmallIntegerField('Возраст', default=0)
    image = models.ImageField('Изображение', upload_to='actors/')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Актеры'
        verbose_name_plural = 'Актеры'


class Movie(models.Model):
    # Список фильмов
    year = models.PositiveSmallIntegerField('Дата выхода', default=2023)
    title = models.CharField('Название', max_length=100)
    category = models.ForeignKey(Categories, verbose_name='Категория', on_delete=models.SET_NULL, null=True, blank=True)
    genre = models.ManyToManyField(Genre, verbose_name='Жанр')
    description = models.TextField('Описание')
    country = models.CharField('Страна', max_length=30)
    actors = models.ManyToManyField(Actors, verbose_name='Актеры', related_name='film_actor')
    image = models.ImageField('Постер', upload_to='movies/')
    url = models.SlugField(max_length=130, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movie_detail', kwargs={'slug': self.url})

    class Meta:
        verbose_name = 'Фильм'
        verbose_name_plural = 'Фильмы'


class RatingFilm(models.Model):
    # Рейтинг фильма
    value = models.FloatField('Рейтинг фильма', default=0)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name='Фильм')

    def __str__(self):
        return f"{self.value} - {self.movie}"

    class Meta:
        verbose_name = 'Рейтинг'
        verbose_name_plural = 'Рейтинги'


class ReviewsFilm(models.Model):
    # Отзывы к фильму
    email = models.EmailField()
    name = models.CharField('Имя пользователя', max_length=100)
    movie = models.ForeignKey(Movie, verbose_name='Фильм', on_delete=models.CASCADE)
    text = models.TextField('Отзыв', max_length=5000)
    history = HistoricalRecords()

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

templates/movies/action_film_list.html
{% extends 'movies/base.html' %}
{% block header %} bg1 {% endblock header %}
{% block title %} Боевики {% endblock title %}
{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for movie in movie_list %}
                <div class="col-md-4 product-men" id="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <a href="{{ movie.get_absolute_url }}">
                                <img src="{{ movie.image.url }}" class="img-fluid" alt="">
                            </a>
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}" class="editContent">
                                    {{ movie.title }}</a>
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <a href="{{ movie.get_absolute_url }}">
                                        <button type="button" class="btn btn-dark">Подробнее</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="pagination justify-content-center my-3">
            <ul class="pagination justify-content-center" style="width: 300px;">
                <li class="page-item row">
                    {% if page_obj.has_previous %}
                        <a class="page-link" href="?page=1">&laquo;</a>
                        <a class="page-link"
                           href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                    {% endif %}
                </li>
                <li class="page-item active">
                    <a class="page-link" href="#">{{ page_obj.number }} <span class="sr-only">(current)</span></a>
                </li>

                <li class="page-item row">
                    {% if page_obj.has_next %}
                        <a class="page-link"
                           href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                        </li>
                    {% endif %}
            </ul>
        </div>

    </div>
{% endblock movie %}
<!-- //contact -->

templates/movies/animation_list.html
{% extends 'movies/base.html' %}
{% block header %} bg1 {% endblock header %}
{% block title %} Мультфильмы {% endblock title %}
{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for movie in movie_list %}
                <div class="col-md-4 product-men" id="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <a href="{{ movie.get_absolute_url }}">
                                <img src="{{ movie.image.url }}" class="img-fluid" alt="">
                            </a>
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}" class="editContent">
                                    {{ movie.title }}</a>
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <a href="{{ movie.get_absolute_url }}">
                                        <button type="button" class="btn btn-dark">Подробнее</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="pagination justify-content-center my-3">
            <ul class="pagination justify-content-center" style="width: 300px;">
                <li class="page-item row">
                    {% if page_obj.has_previous %}
                        <a class="page-link" href="?page=1">&laquo;</a>
                        <a class="page-link"
                           href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                    {% endif %}
                </li>
                <li class="page-item active">
                    <a class="page-link" href="#">{{ page_obj.number }} <span class="sr-only">(current)</span></a>
                </li>

                <li class="page-item row">
                    {% if page_obj.has_next %}
                        <a class="page-link"
                           href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                        </li>
                    {% endif %}
            </ul>
        </div>

    </div>
{% endblock movie %}
<!-- //contact -->

templates/movies/base.html
{% extends 'base.html' %}
{% block title %} БилетыОнлайн {% endblock title %}
{% block content %}
    <section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem;">
        <!-- {% block container %}
            <div class="container-fluid py-md-3">
        {% endblock container %} -->
        <div class="row">
            {% block sidebar %}
                <div class="side-bar col-lg-3">
            {% endblock sidebar %}
            {% include 'include/sidebar.html' %}
            </div>
            {% block movie %}
            {% endblock movie %}
        </div>
        </div>
    </section>
{% endblock content %}

templates/movies/cartoon_list.html
{% extends 'movies/base.html' %}
{% block header %} bg1 {% endblock header %}
{% block title %} Анимации {% endblock title %}
{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for movie in movie_list %}
                <div class="col-md-4 product-men" id="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <a href="{{ movie.get_absolute_url }}">
                                <img src="{{ movie.image.url }}" class="img-fluid" alt="">
                            </a>
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}" class="editContent">
                                    {{ movie.title }}</a>
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <a href="{{ movie.get_absolute_url }}">
                                        <button type="button" class="btn btn-dark">Подробнее</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="pagination justify-content-center my-3">
            <ul class="pagination justify-content-center" style="width: 300px;">
                <li class="page-item row">
                    {% if page_obj.has_previous %}
                        <a class="page-link" href="?page=1">&laquo;</a>
                        <a class="page-link"
                           href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                    {% endif %}
                </li>
                <li class="page-item active">
                    <a class="page-link" href="#">{{ page_obj.number }} <span class="sr-only">(current)</span></a>
                </li>

                <li class="page-item row">
                    {% if page_obj.has_next %}
                        <a class="page-link"
                           href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                        </li>
                    {% endif %}
            </ul>
        </div>

    </div>
{% endblock movie %}
<!-- //contact -->

templates/movies/comedy_list.html
{% extends 'movies/base.html' %}
{% block header %} bg1 {% endblock header %}
{% block title %} Комедии {% endblock title %}
{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for movie in movie_list %}
                <div class="col-md-4 product-men" id="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <a href="{{ movie.get_absolute_url }}">
                                <img src="{{ movie.image.url }}" class="img-fluid" alt="">
                            </a>
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}" class="editContent">
                                    {{ movie.title }}</a>
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <a href="{{ movie.get_absolute_url }}">
                                        <button type="button" class="btn btn-dark">Подробнее</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="pagination justify-content-center my-3">
            <ul class="pagination justify-content-center" style="width: 300px;">
                <li class="page-item row">
                    {% if page_obj.has_previous %}
                        <a class="page-link" href="?page=1">&laquo;</a>
                        <a class="page-link"
                           href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                    {% endif %}
                </li>
                <li class="page-item active">
                    <a class="page-link" href="#">{{ page_obj.number }} <span class="sr-only">(current)</span></a>
                </li>

                <li class="page-item row">
                    {% if page_obj.has_next %}
                        <a class="page-link"
                           href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                        </li>
                    {% endif %}
            </ul>
        </div>

    </div>
{% endblock movie %}
<!-- //contact -->

templates/movies/fantastic_list.html
{% extends 'movies/base.html' %}
{% block header %} bg1 {% endblock header %}
{% block title %} Фантастика {% endblock title %}
{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for movie in movie_list %}
                <div class="col-md-4 product-men" id="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <a href="{{ movie.get_absolute_url }}">
                                <img src="{{ movie.image.url }}" class="img-fluid" alt="">
                            </a>
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}" class="editContent">
                                    {{ movie.title }}</a>
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <a href="{{ movie.get_absolute_url }}">
                                        <button type="button" class="btn btn-dark">Подробнее</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="pagination justify-content-center my-3">
            <ul class="pagination justify-content-center" style="width: 300px;">
                <li class="page-item row">
                    {% if page_obj.has_previous %}
                        <a class="page-link" href="?page=1">&laquo;</a>
                        <a class="page-link"
                           href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                    {% endif %}
                </li>
                <li class="page-item active">
                    <a class="page-link" href="#">{{ page_obj.number }} <span class="sr-only">(current)</span></a>
                </li>

                <li class="page-item row">
                    {% if page_obj.has_next %}
                        <a class="page-link"
                           href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                        </li>
                    {% endif %}
            </ul>
        </div>

    </div>
{% endblock movie %}
<!-- //contact -->

templates/movies/moscino-saturn.html
{% extends 'movies/base.html' %}
{% load i18n static templatetag %}
{% block title %} ПаркХаус {% endblock %}
{% block header %} bg1 {% endblock header %}

{% block content %}
    <div class="" style="width: 98vw">
        <div class="mx-auto text-center" style="width: 760px">
            {% get_moscino as moscino %}
            <h4 class="mt-5 mb-3">
                <span class="editContent"> {{ moscino }}</span>
            </h4>

            <h6 class="mb-3">
                <span class="editContent"> {{ moscino.description }}</span>
            </h6>

            <h6 class="mb-3">
                {% trans 'Контактный номер' %}:
                <a href="tel:{{ moscino.number }}">{{ moscino.number }}</a>
            </h6>
            <h6 class="mb-5">
            <a target="_blank" href="https://yandex.ru/maps/213/moscow/house/snezhnaya_ulitsa_18/Z04YcANnTEQEQFtvfXR0cHVlYQ==/?ll=37.647513%2C55.851965&z=16.81">
                {{ moscino.address }}
            </a>
                </h6>
        </div>
    </div>


{% endblock content %}

templates/movies/movie_detail.html
{% extends 'movies/base.html' %}
{% load i18n static %}
{% block title %} {{ movie.title }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6 text-center">
                <img src="{{ movie.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    {{ movie.title }}</h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li class="mb-3" style="list-style: none"><span><b>{% trans 'Год' %}:</b> {{ movie.year }}</span></li>
                    <li class="mb-3" style="list-style: none"><span><b>{% trans 'Страна' %}:</b> {{ movie.country }}</span>
                    </li>
                    <li class="mb-3" style="list-style: none"><span><b>{% trans 'В главных ролях' %}:</b>
                        {% for actor in movie.actors.all %}
                            <ul>{{ actor.name }}</ul>
                        {% endfor %}</span></li>
                    <li class="mb-3" style="list-style: none"><span><b>{% trans 'Жанр' %}: </b>
                        {% for genre in movie.genre.all %}
                            <ul>{{ genre.name }}</ul></span>
                        {% endfor %}
                    </li>
                    <li style="list-style: none">
                        <a href="#"><b>{% trans 'Рейтинг' %}:</b>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="editContent"
                                  style="outline: none; cursor: inherit;">5.0</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent text-center" style="outline: none; cursor: inherit; width: 760px;">
                {% if movie.category_id == 2 %}
                    {% trans 'О мультфильме' %} {{ movie.title }}
                {% endif %}
                {% if movie.category_id == 1 %}
                    {% trans 'О фильме' %} {{ movie.title }}
                {% endif %}
            </h3>
            <p class="editContent" style="outline: none; cursor: inherit;">{{ movie.description|safe }}</p>
        </div>
        <hr style="width: 760px" class="mx-auto">
        <div class="row sub-para-w3layouts mt-5">
            <div class="single-form-left col-lg-9">
                <!-- contact form grid -->
                <div class="contact-single mx-auto" style="width: 760px">
                    <h3 class="editContent text-center" style="outline: none; cursor: inherit; width:760px;">
                                    <span class="sub-tittle editContent"
                                          style="outline: none; cursor: inherit;"></span>{% trans 'Оставить отзыв' %}</h3>
                    <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4">
                        {% csrf_token %}
                        <div class="form-group editContent"
                             style="outline: none; cursor: inherit;">
                            <label for="contactcomment" class="editContent"
                                   style="outline: none; cursor: inherit;">{% trans 'Ваш отзыв' %}</label>
                            <textarea class="form-control border" rows="5"
                                      id="contactcomment" required="" name="text"
                                      placeholder="{% trans 'Введите ваш отзыв' %}"></textarea>
                        </div>
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group p-0 editContent"
                                 style="outline: none; cursor: inherit;">
                                <label for="contactusername" class="editContent"
                                       style="outline: none; cursor: inherit;">{% trans 'Ваше имя' %}</label>
                                <input type="text" class="form-control border"
                                       id="contactusername" required="" name="name" placeholder="{% trans 'Введите ваше имя' %}">
                            </div>
                            <div class="col-sm-6 form-group ml-sm-3 editContent"
                                 style="outline: none; cursor: inherit;">
                                <label for="contactemail" class="editContent"
                                       style="outline: none; cursor: inherit;">{% trans 'Ваш' %}email</label>
                                <input type="email" class="form-control border"
                                       id="contactemail" required="" name="email"
                                       placeholder="{% trans 'Введите адрес электронной почты' %}">
                            </div>
                        </div>
                        <button type="submit"
                                class="mt-3 btn btn-outline-success btn-block py-3"
                                style="outline: none; cursor: inherit;">{% trans 'Отправить' %}
                        </button>
                    </form>
                </div>
                <!--  //contact form grid ends here -->
            </div>
        </div>
        <div class="column mt-5">
            <h3 class="editContent text-center" style="outline: none; cursor: inherit; width:760px;">
                                    <span class="sub-tittle editContent"
                                          style="outline: none; cursor: inherit;"></span>{% trans 'Отзывы' %}({{ movie.reviewsfilm_set.count }})
            </h3>
            <div class="section mt-5">
                {% for review in movie.reviewsfilm_set.all %}
                    <div class="media mb-4">
                        <img src="{% static '/images/reviewers.jpg' %}" class="my-2 img-fluid" alt="image">
                        <div class="media-body mt-4 ml-4">
                            <h5 class="mt-0 editContent">{{ review.name }}</h5>
                            <p class="mt-2 editContent">
                                {{ review.text }}
                            </p>
                            {#                    <div class="media mt-5 editContent"#}
                            {#                         style="outline: none; cursor: inherit;">#}
                            {#                        <a class="pr-3" href="#">#}
                            {#                            <img src="bundles/images/te1.jpg" class="img-fluid "#}
                            {#                                 alt="image" style="outline: none; cursor: inherit;">#}
                            {#                        </a>#}
                            {#                        <div class="media-body">#}
                            {#                            <h5 class="mt-0 editContent"#}
                            {#                                style="outline: none; cursor: inherit;">Leia Organa</h5>#}
                            {#                            <p class="mt-2 editContent"#}
                            {#                               style="outline: none; cursor: inherit;"> Cras sit amet#}
                            {#                                nibh libero, in gravida nulla. Nulla vel metus#}
                            {#                                scelerisque ante sollicitudin. Cras purus odio,#}
                            {#                                vestibulum in vulputate at, tempus viverra turpis. Fusce#}
                            {#                                condimentum nunc ac nisi vulputate fringilla..</p>#}
                            {#                        </div>#}
                            {#                    </div>#}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    </div>
    </div>
{% endblock movie %}